version: '3.3'

services:
  mongu:
      restart: on-failure
      image: mongo:4.4-focal  
      ports: 
       - "27017:27017"
      # environment:
      #   MONGO_INITDB_ROOT_USERNAME: geleia
      #   MONGO_INITDB_ROOT_PASSWORD: senhageleia